name: 'Signed Tag'
description: 'GitHub Action to replace given tag with a signed tag by using a GitHub App access tokens and the GitHub API'
author: 'qoomon'
branding:
  icon: git-commit
  color: blue

inputs:
  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
  working-directory:
    description: 'The working directory'
    required: true
    default: '.'
  remoteName:
    description: 'The remote name to create the tag at.'
    required: true
    default: 'origin'
  name:
    description: 'The tag name'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
