name: 'Create GitHub Tag'
description: 'Create Tag'
author: 'qoomon'
branding:
  icon: git-commit
  color: blue

inputs:
  name:
    description: 'The tag name'
    required: true
  message:
    description: 'The annotated tag message'

  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
  working-directory:
    description: 'The working directory'
    required: true
    default: '.'
  remoteName:
    description: 'The remote name to create the tag at.'
    required: true
    default: 'origin'

runs:
  using: 'node20'
  main: 'dist/index.js'
