name: 'Signed Tag'
description: 'GitHub Action to create signed tag from within a GitHub Action workflow'
author: 'qoomon'
branding:
  icon: git-commit
  color: blue

inputs:
  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
  working-directory:
    description: 'The working directory'
    required: true
    default: '.'
  remoteName:
    description: 'The remote name to create the commit on'
    required: true
    default: 'origin'
  name:
    description: 'The tag name'
    required: true

outputs:
  tag:
    description: 'The SHA of the tag'

runs:
  using: 'node20'
  main: 'dist/index.js'
