name: Release Action

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref'
        required: true
        default: 'main'
      version:
        description: 'Version'
        required: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: qoomon/actions--tag@v1
        with:
          name: v${{ inputs.version }}
          message: 'Release ${{ inputs.version }}'
      - run: git push origin "v${{ inputs.version }}"
      - run: |
          # move the major version tag e.g. v1
          MAJOR_RELEASE_VERSION="${RELEASE_VERSION_TAG%%.*}"
          MAJOR_RELEASE_VERSION_TAG="v${MAJOR_RELEASE_VERSION}"
          git tag --force "${MAJOR_RELEASE_VERSION_TAG}"
          git push --force origin "${MAJOR_RELEASE_VERSION_TAG}"
        env:
          RELEASE_VERSION: ${{ inputs.version }}

#          run: |
#            if [ -z "$RELEASE_VERSION" ]
#            then
#              exit 1
#            fi
#
#            RELEASE_VERSION_TAG="v$RELEASE_VERSION"
#            git tag -a -m "${RELEASE_VERSION}" "${RELEASE_VERSION_TAG}"
#            git push origin "${RELEASE_VERSION_TAG}"
#
#            # move the major version tag e.g. v1
#            git tag --force "${RELEASE_VERSION_TAG%%.*}"
#            git push --force origin "${RELEASE_VERSION_TAG%%.*}"
